#!/usr/bin/env bash

sudo -v

# Get the path of the directory in which the script is loacted.
SOURCE="${BASH_SOURCE[0]}"
# Resolve $SOURCE until the file is no longer a symlink.
while [ -h "$SOURCE" ]; do
	DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
	SOURCE="$(readlink "$SOURCE")"
	# If $SOURCE was a relative symlink we need to resolve it relative to
	# the path where the symlink file was located.
	[[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

# Setup OS X defaults.
$DIR/osx

# Install homebrew and install packages.
which brew > /dev/null
if [[ $? -ne 0 ]]; then
	ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi
brew install $(paste -s $DIR/brew)
brew cask install $(paste -s $DIR/cask)

# Link dot files.
for i in $(ls $DIR/dot); do
	if [ ! -L "$HOME/.$i" ]; then
		echo "Linking $DIR/dot/$i to $HOME/.$i"
		ln -sf "$DIR/dot/$i" "$HOME/.$i"
	fi
done

# Setup fish.
FISH="$HOME/.config/fish"
[[ ! -d $FISH ]] && mkdir -p "$FISH"
for i in $(ls "$DIR/fish"); do
	if [ ! -L "$FISH/$i" ]; then
		echo "Linking $DIR/fish/$i to $FISH/$i"
		ln -sf "$DIR/fish/$i" "$FISH/$i"
	fi
done

# Setup Vim.
if [ ! -f $HOME/.vim/autoload/plug.vim ]; then
	curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
		https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi
mvim -v +PlugInstall +PluginClean! +qall

# Setup Haskell.
cabal update
cabal install $(paste -s $DIR/cabal)
