#!/bin/bash

# Install homebrew and install packages.
which brew > /dev/null
if [[ $? -ne 0 ]]; then
	ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi
brew install $(paste -s brew)
brew cask install $(paste -s cask)

# Setup zsh.
[[ ! -d ~/.oh-my-zsh ]] && curl -L http://install.ohmyz.sh | sh

# Link dot files.
for i in $(ls dot); do
	if [ ! -L "$HOME/.$i" ]; then
		echo "Linking $HOME/etc/dot/ to $HOME/.$i"
		ln -sf "$HOME/etc/dot/$i" "$HOME/.$i"
	fi
done

# Setup vim.
[[ ! -d ~/.vim/bundle ]] && mkdir -p ~/.vim/bundle
if [ ! -d ~/.vim/bundle/vundle ]; then
	git clone https://github.com/gmarik/vundle ~/.vim/bundle/vundle
fi
vim +PluginInstall +qall
