#!/usr/bin/env bash

# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing `sudo` time stamp until finished.
while true; do sudo -n true; sleep 60; kill -0 $$ || exit; done 2>/dev/null &

# Get the path of the directory in which the script is loacted.
SOURCE=${BASH_SOURCE[0]}
# Resolve $SOURCE until the file is no longer a symlink.
while [[ -h $SOURCE ]]; do
        DIR=$(cd -P $(dirname $SOURCE) && pwd)
        SOURCE=$(readlink $SOURCE)
        # If $SOURCE was a relative symlink we need to resolve it relative to
        # the path where the symlink file was located.
        [[ $SOURCE != /* ]] && SOURCE=$DIR/$SOURCE
done
DIR=$(cd -P $(dirname $SOURCE) && pwd)

for i in $(ls $DIR/dot); do
	echo Linking $DIR/dot/$i to $HOME/.$i
	ln -sf $DIR/dot/$i "$HOME/.$i"
done

curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
        https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
for i in $(ls $DIR/vim); do
        ln -sf $DIR/vim/$i "$HOME/.vim/"
done

echo Linking $DIR/stack/config.yaml to $HOME/.stack/config.yaml
if [[ ! -d $HOME/.stack ]]; then
        mkdir $HOME/.stack
fi
ln -sf $DIR/stack/config.yaml $HOME/.stack/config.yaml
