export EDITOR='vim'

export PATH=~/bin:$PATH
# Go.
export GOPATH=$HOME/go
PATH=$PATH:$GOPATH/bin
# Haskell.
PATH=$PATH:$HOME/.cabal/bin

# OPAM configuration
. /Users/jji/.opam/opam-init/init.sh > /dev/null 2> /dev/null || true

[[ -r ~/.bashrc ]] && . ~/.bashrc

[[ -z $TMUX ]] && exec tmux
